### ISSUE TITLE
[QUESTION]Can Decorators take place of  pyhooks?

### ISSUE THREAD

**Issue by thouger** [Shir0kamii/pyhooks#6]
I came to this repo to learn hooks technology.After i see the theory,have doubts about what do pyhooks solve better than Python Decorators.Pyhooks and Decorators have same principle that can execute code before or after a method.For [the example](https://github.com/Shir0kamii/pyhooks#how-to-use-) using in Pyhooks repo can use Python Decorators:
```
def hook(func):
    def wrapper(*args,**kwargs):
        self=args[0]
        self.version+=1
    return wrapper

class DatabaseEntry(object):
    version = 0
    @hook
    def save(self):
        print('save data')

database_entry=DatabaseEntry()
database_entry.save()
database_entry.save()
database_entry.save()
print(database_entry.version)
```

**Comment by Shir0kamii** [comment]
Hi,

Pyhooks is in fact built to work with classes that you don't define yourself. You can use a simple decorator in this case because you define the DatabaseEntry class yourself. However, when you want to do this for a third party class, pyhooks will allow less boilerplate, as you won't have to override the function to change its behavior.

When you want to do that for one of your own classes, a simpler approach without pyhooks works better.

**Comment by thouger** [comment]
Thank @Shir0kamii ,i already know what does Pyhooks do.In general,Pyhooks is a wrapper around Decorators.If i want to implement AOP（Aspect Oriented Programming）,Pyhooks can let me implement it directly rather than by rewriting Decorators.On the other hand,it can be used by people who don't know much about Decorators.After all Decorators is too hard to understand with callbacks and parameters.By the way, i want to disclose the  secret about the code is so hard to understand in order that I was already confused when I read it.
![4l 1s9zfc9 p_ vsi kotsm](https://user-images.githubusercontent.com/11767062/51581895-f444f180-1f04-11e9-840a-cfc849466e1f.jpg)
